name: Run deployment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform:
    name: Terraform for ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform init -backend-config="resource_group_name=Cloud-Final-Project-${{ inputs.environment }}"
        working-directory: terraform
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      - name: Terraform plan 
        working-directory: terraform
        run: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_ENV: ${{ inputs.environment }}
          TF_VAR_PSQL_USERNAME: ${{ secrets.PSQL_USERNAME }}
          TF_VAR_PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD }}
      - name: Terraform apply 
        working-directory: terraform
        run: terraform apply --auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_ENV: ${{ inputs.environment }}
          TF_VAR_PSQL_USERNAME: ${{ secrets.PSQL_USERNAME }}
          TF_VAR_PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD }}

  build_api:
    runs-on: ubuntu-latest
    needs: terraform
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install packages
      run: yarn
    - name: Build Prisma client
      run: yarn prisma:gen
    - name: Build
      run: yarn build
    - name: Zip all files for upload between jobs
      run: zip --symlinks -r nest.zip ./*
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: ./api/nest.zip

  deploy_api:
    name: Deploy API
    runs-on: ubuntu-latest
    needs: build_api
    environment: ${{ inputs.environment }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
      - name: Login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: cloud-fp-${{ inputs.environment }}-api
          package: nest.zip
      - name: Delete zip file
        run: rm ./nest.zip

  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: terraform
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x 
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Zip all files for upload between jobs
        run: zip --symlinks -r web.zip * .[^.]*
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: ./web/web.zip

  deploy_web:
    name: Build and Deploy Web
    runs-on: ubuntu-latest
    needs: build_web
    environment: ${{ inputs.environment }}
    steps:
      - name: Login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: web-app
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: cloud-fp-${{ inputs.environment }}-web
          package: ./web.zip
      - name: Delete zip file
        run: rm ./web.zip


      
