name: Run deployment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform:
    name: Build infrastructure for ${{ inputs.environment }} using terraform.
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform init -backend-config="resource_group_name=Cloud-Final-Project-${{ inputs.environment }}"
        working-directory: terraform
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      - name: Terraform plan 
        working-directory: terraform
        run: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_ENV: ${{ inputs.environment }}
          TF_VAR_PSQL_USERNAME: ${{ secrets.PSQL_USERNAME }}
          TF_VAR_PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD }}
      - name: Terraform apply 
        working-directory: terraform
        run: terraform apply --auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_ENV: ${{ inputs.environment }}
          TF_VAR_PSQL_USERNAME: ${{ secrets.PSQL_USERNAME }}
          TF_VAR_PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD }}

  deploy_api:
    name: Build and Deploy API
    runs-on: ubuntu-latest
    needs: terraform
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x 
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: cloud-fp-api-${{ inputs.environment }}
          publish-profile: ${{ secrets.API_PUBLISH_PROFILE }}
          package: ./api/dist

  deploy_web:
    name: Build and Deploy Web
    runs-on: ubuntu-latest
    needs: deploy_api
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x 
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: cloud-fp-api-${{ inputs.environment }}
          publish-profile: ${{ secrets.WEB_PUBLISH_PROFILE }}
          package: ./api/.next


      
