name: Multi stage deployment of the application.
run-name: ${{ github.actor }} triggered deployment.
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_staging:
    name: Deploy to staging environment
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: "staging"
    secrets: inherit
  
  deploy_production:
    runs-on: ubuntu-latest
    name: Deploy to production environment
    needs: deploy_staging
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: berkeli
      - name: Deploy to production environment
        uses: ./.github/workflows/deploy.yaml
        with:
          environment: "production"
