name: Multi stage deploy
run-name: ${{ github.actor }} triggered deployment.
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Everything
    uses: ./.github/workflows/lint_and_test.yaml

  deploy_staging:
    needs: test
    name: Deploy staging
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: "staging"
    secrets: inherit
  
  deploy_production:
    runs-on: ubuntu-latest
    name: Deploy production
    needs: deploy_staging
    steps:
      - name: Deploy to production environment
        uses: ./.github/workflows/deploy.yaml
        with:
          environment: "production"
